salary:
  logical_operator: AND
  identifiers:
    - value:
      comparison_operator: ">="
      column: "Credit"
    - value: "Salary"
      comparison_operator: "contains"
      column: "Transaction Type"
expense_categories:
  - name: House related
    logical_operator: OR
    identifiers:
      - value:
        comparison_operator: ">="
        label: "Rent"
        column: "Debit"
      - value: "Marius"
        comparison_operator: "contains"
        label: "Everything else Marius"
        column: "Payment Details"
  - name: Food
    logical_operator: OR
    identifiers:
      - value:
        comparison_operator: "contains"
        label: "Diska"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Edeka"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Aldi"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Simmel"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Tukwila"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Konsum"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Rewe"
        column: "Payment Details"
  - name: Cash
    logical_operator: OR
    identifiers:
      - value:
        comparison_operator: "=="
        column: "Transaction Type"
        label: "Withdraw cash"
  - name: Retail
    logical_operator: OR
    identifiers:
      - value:
        comparison_operator: "contains"
        label: "Amazon"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Tickets"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Tickets"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Electronics"
        column: "Payment Details"
      - value:
        comparison_operator: "contains"
        label: "Electronics"
        column: "Payment Details"
